name: CI

on:
  pull_request:
    paths-ignore:
    - '**/*.md'
    - 'docs/**/*'
    - '.readthedocs.yaml'
  push:
    paths-ignore:
    - '**/*.md'
    - 'docs/**/*'
    - '.readthedocs.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: cachix/install-nix-action@v13
    - uses: actions/checkout@v2
    - uses: cachix/cachix-action@v10
      with:
        name: tezos-checker
        authToken: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Build and test
      run: nix-build -A michelson --arg doCheck true --arg isCi true
